<a href="https://colab.research.google.com/github/castrokelly/MBA/blob/main/Numpy_I_avaliacao_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte I - Avaliação</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

## <font color='red'> As respostas da avaliação devem ser inseridas no moodle </font>

In [1]:
import numpy as np

### Exercício 1)
Considere o array `X` como descrito abaixo:
```python
[[0  1  2  3  4]
 [5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
```
Qual dos códigos abaixo imprime um array com os elementos 13, 18 e 6 a partir de `X`?

a) print(X[1,2,3])<br>
b) print(X[[2,3,1],[3,3,1]]) -----------> MINHA RESPOSTA</font> <br>
c) print(X[:,[2,3,1])<br>
d) print([1,2,3],:)

In [12]:
import numpy as np

X = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14],
              [15, 16, 17, 18, 19]])

# Acessar os elementos específicos
result = X[[2, 3, 1], [3, 3, 1]]

print(result)


[13 18  6]


### Exercício 2)
Considerando o array `X` do exercício 1). Qual alternativa descreve corretamente a construção de `Y` no código abaixo?
```python
Y = X[1:3,[0,2,3]]
```

a) `Y` é uma _cópia_ dos elementos das linhas 1 e 2 e colunas 0,2 e 3 de `X`<br>
b) `Y` é uma _view_ dos elementos das linhas 1 e 2 e colunas 0,2 e 3 de `X` ------------> MINHA RESPOSTA<br>
c) `Y` é uma _cópia_ dos elementos das linhas 1,2 e 3 e colunas 0,2 e 3 de `X`<br>
d) `Y` é uma _view_ dos elementos das linhas 1,2 e 3 e colunas 0,2 e 3 de `X`

In [3]:
Y = X[1:3,[0,2,3]]


### Exercício 3)
Considere o numpy array `A` abaixo:
```python
[[ 2 19 16  1 12  7]
 [ 5 19 18 17  9  3]
 [16  4 18 11  4  2]
 [ 6  2 18 14 15 15]
 [ 4  8  1 14 19 13]]
```
Qual das alternativas abaixo corresponde ao número de dimensões (ndim), a forma (shape) e ao número de elementos (size) no array, respectivamente?

a) (5, 6) 2 2<br>
b) 2 (5, 6) 2<br>
c) (5, 6) 2 30<br>
d) 2 (5, 6) 30 -------> MINHA RESPOTA

In [4]:
A = np.array([[ 2, 19, 16,  1, 12,  7],
 [ 5, 19, 18, 17,  9,  3],
 [16,  4, 18, 11,  4,  2],
 [ 6,  2, 18, 14, 15, 15],
 [ 4,  8,  1, 14, 19, 13]])


Número de dimensões (ndim): Este é o número de índices necessários para selecionar um elemento do array. No caso de A, que é um array 2D (duas dimensões), o ndim seria 2.</br>
</br>
Forma (shape): A forma de um array é uma tupla que indica o número de elementos em cada dimensão. Para A, que tem 5 linhas e 6 colunas, o shape seria (5, 6).</br>
</br>
Número de elementos (size): Este é o total de elementos no array. Para A, que tem 5 linhas e 6 colunas, o size seria 5 * 6 = 30.</br>
Portanto, a alternativa correta que descreve o número de dimensões, a forma e o número de elementos no array A, respectivamente, é:

c. 2 (5, 6) 30

### Exercício 4)
Considere o numpy array `A` do exercício 3). Escreva um código para criar uma máscara para selecionar todos os elementos pares do array e armazena-los em um novo array *unidimensional* `B`. O resultado do comando
```python
print(B.size)
```
será:<br>
a) 13<br>
b) 15<br>
c) 16<br>
d) 17

In [13]:
import numpy as np

# Definindo o numpy array A
A = np.array([[2, 19, 16,  1, 12,  7],
              [5, 19, 18, 17,  9,  3],
              [16,  4, 18, 11,  4,  2],
              [6,  2, 18, 14, 15, 15],
              [4,  8,  1, 14, 19, 13]])

# Criando uma máscara para selecionar todos os elementos pares de A
mask = A % 2 == 0

# Usando a máscara para selecionar os elementos e armazenando em B
B = A[mask]

# Imprimindo o tamanho de B
B.size


16

### Exercício 5)
Ainda considerando o array `A` do exercício 3), que alternativa melhor explica o que o código abaixo está realizando:
```python
l_mask = [(i%2!=0) and (j%2!=0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1
```
a) insere elementos -1 nas linhas e colunas ímpares de `A` utilizando uma máscara booleana<br>
b) insere elementos -1 nas posições com índices ímpares (linha e coluna) de `A` utilizando uma máscara booleana  -------> MINHA RESPOSTA<br>
c) insere elementos -1 nas linhas com índices ímpares e colunas pares de `A` utilizando uma máscara booleana<br>
d) troca os elementos impares da matriz por -1 utilizando uma máscara booleana

In [6]:
l_mask = [(i%2!=0) and (j%2!=0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1
print(A)

[[ 2 19 16  1 12  7]
 [ 5 -1 18 -1  9 -1]
 [16  4 18 11  4  2]
 [ 6 -1 18 -1 15 -1]
 [ 4  8  1 14 19 13]]
